function Gd = compute_displacementkernels(obs,ss,shz,src)

xo = obs(:,1);
zo = obs(:,2);

% Displacement Kernels for distributed deformation
uk12=@(D,L,W,x2,x3) 1/(2*pi)*( ...
    (x3-D-W).*log((x2-L/2).^2+(x3-D-W).^2) ...
    -(x3-D-W).*log((x2+L/2).^2+(x3-D-W).^2) ...
    -(x3-D).*log((x2-L/2).^2+(x3-D).^2) ...
    +(x3-D).*log((x2+L/2).^2+(x3-D).^2) ...
    +2*(x2-L/2).*(atan((x3-D-W)./(x2-L/2))-atan((x3-D)./(x2-L/2))) ...
    +2*(x2+L/2).*(atan((x3-D)./(x2+L/2))-atan((x3-D-W)./(x2+L/2))) ...
    +(x3+D+W).*log((x2+L/2).^2+(x3+D+W).^2) ...
    -(x3+D+W).*log((x2-L/2).^2+(x3+D+W).^2) ...
    -(x3+D).*log((x2+L/2).^2+(x3+D).^2) ...
    +(x3+D).*log((x2-L/2).^2+(x3+D).^2) ...
    +2*(x2+L/2).*(atan((x3+D+W)./(x2+L/2))-atan((x3+D)./(x2+L/2))) ...
    +2*(x2-L/2).*(atan((x3+D)./(x2-L/2))-atan((x3+D+W)./(x2-L/2))) ...
    );

uk13=@(D,L,W,x2,x3) 1/(2*pi)*( ...
    (x2-L/2).*log((x2-L/2).^2+(x3-D-W).^2) ...
    -(x2+L/2).*log((x2+L/2).^2+(x3-D-W).^2) ...
    -(x2-L/2).*log((x2-L/2).^2+(x3-D).^2) ...
    +(x2+L/2).*log((x2+L/2).^2+(x3-D).^2) ...
    +2*(x3-W-D).*(atan((x2-L/2)./(x3-D-W))-atan((x2+L/2)./(x3-D-W))) ...
    +2*(x3-D).*(atan((x2+L/2)./(x3-D))-atan((x2-L/2)./(x3-D))) ...
    +(x2-L/2).*log((x2-L/2).^2+(x3+D+W).^2) ...
    -(x2+L/2).*log((x2+L/2).^2+(x3+D+W).^2) ...
    -(x2-L/2).*log((x2-L/2).^2+(x3+D).^2) ...
    +(x2+L/2).*log((x2+L/2).^2+(x3+D).^2) ...
    +2*(x3+W+D).*(atan((x2-L/2)./(x3+D+W))-atan((x2+L/2)./(x3+D+W))) ...
    +2*(x3+D).*(atan((x2+L/2)./(x3+D))-atan((x2-L/2)./(x3+D))) ...
    );

% Displacement kernels for fault slip
u1h=@(x2,x3,y2,y3,W) ...
    (+atan((x3-y3)./(x2-y2))-atan((x3+y3)./(x2-y2)) ...
     -atan((x3-y3-W)./(x2-y2))+atan((x3+y3+W)./(x2-y2)) ...
    )/2/pi;

% Displacement Kernels for Fault Slip
Gd.kd = zeros(length(xo),ss.M);
if isfield(ss,'Lf')
    for k = 1:ss.M
        Gd.kd(:,k) = uk12(ss.y3f(k),ss.Lf(k),ss.Wf(k),xo-ss.y2c(k),zo);
    end
else
    for k = 1:ss.M
        Gd.kd(:,k) = u1h(xo,zo,ss.y2f(k),ss.y3f(k),ss.Wf(k));
    end
end

% Displacement Kernels for Strain Volumes
Gd.l12d = zeros(length(xo),shz.N);
Gd.l13d = Gd.l12d;

for k = 1:shz.N
    if isfield(shz,'L')==1
        Gd.l12d(:,k) = uk12(shz.xx3c(k)-shz.W(k)/2,shz.L(k),shz.W(k),xo-shz.xx2c(k),zo);
        Gd.l13d(:,k) = uk13(shz.xx3c(k)-shz.W(k)/2,shz.L(k),shz.W(k),xo-shz.xx2c(k),zo);
    elseif isfield(shz,'tri')==1
        %x2c = mean([shz.A(:,1),shz.B(:,1),shz.C(:,1)],2);
        %x3c = mean([shz.A(:,2),shz.B(:,2),shz.C(:,2)],2);
        
        u1=computeDisplacementAntiplaneTriangleShearZone(xo,zo,shz.A(k,:),shz.B(k,:),shz.C(k,:),1,0);
        Gd.l12d(:,k) = u1;
        u1=computeDisplacementAntiplaneTriangleShearZone(xo,zo,shz.A(k,:),shz.B(k,:),shz.C(k,:),0,1);
        Gd.l13d(:,k) = u1;
    else
        disp('Not recognized shz structure')
    end
end

%% If src exists
if nargin==4
    Gd.src12d = uk12(src.xx3c-src.W/2,src.L,src.W,xo-src.xx2c,zo);
end

end